apiVersion: v1
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    spec:
      lookupPolicy:
        local: false
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        build: ocp101-helloworld
        app: ocp101-helloworld
      name: ${NAME}
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: '${NAME}:latest'
      postCommit: {}
      resources: {}
      source:
        git:
          uri: 'https://github.com/patricksimonian/ocp101-helloworld'
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: 'nodejs:10'
            namespace: openshift
        type: Source
      triggers:
        - github:
            secret: ffEmY3K42Ld8FvgSqMwe
          type: GitHub
        - generic:
            secret: TW5zZaFYMGFERp7V0Jsb
          type: Generic
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        build: ocp101-helloworld
        app: ocp101-helloworld
      name: ocp101-helloworld
kind: Template
parameters: 
- name: NAME
  displayName: Object Name
  description: The name given to build config template objects
  required: true
metadata: {}
